### ISSUE TITLE
get_range not returning all the rows

### ISSUE THREAD

**Issue by Simbul** [cassandra-rb/cassandra#117]
Hello,
I'm a bit puzzled by a weird behavior with the get_range method.

I've got a Cassandra data store that's been used for a couple of weeks, with various additions and removals. I'm now in a situation where:

```
cassandra.get_range(:ColumnFamily) # -> returns 34 rows
cassandra.get_range(:ColumnFamily, :key_count => 1000) # -> returns 515 rows
cassandra.get_range(:ColumnFamily, :batch_size => 100) # -> returns 515 rows
```

I would have been fine if the first call had returned 100 items (which seems to be the default limit), but the number I'm getting has got me really wondering what could be going on here.

Have you got any idea where this weird behavior could be coming from?

**Comment by rwjblue** [comment]
Cassandra stores a tombstone for deleted rows and columns for gc_grace_seconds (defaults to 864000 seconds)[1]. This means that a row is returned for each key that is present, but they may not all have columns (that are not deleted). Because of this get_range only returns rows that have at least one column. 

So in your first example 34 of the first 100 keys have at least one column. 

In the second and third examples you see that your total count of rows (that have at least one column) is 515. 

[1] - http://wiki.apache.org/cassandra/FAQ#range_ghosts 

Robert Jackson 

----- Original Message -----

From: "Alessandro Morandi" reply@reply.github.com 
To: "Robert Jackson" robertj@promedicalinc.com 
Sent: Thursday, September 8, 2011 3:14:44 PM 
Subject: [cassandra] get_range not returning all the rows (#117) 

Hello, 
I'm a bit puzzled by a weird behavior with the get_range method. 

I've got a Cassandra data store that's been used for a couple of weeks, with various additions and removals. I'm now in a situation where: 

cassandra.get_range(:ColumnFamily) # -> returns 34 rows 
cassandra.get_range(:ColumnFamily, :key_count => 1000) # -> returns 515 rows 
cassandra.get_range(:ColumnFamily, :batch_size => 100) # -> returns 515 rows 

I would have been fine if the first call had returned 100 items (which seems to be the default limit), but the number I'm getting has got me really wondering what could be going on here. 

Have you got any idea where this weird behavior could be coming from? 

## 

Reply to this email directly or view it on GitHub: 
https://github.com/fauna/cassandra/issues/117

**Comment by Simbul** [comment]
I considered deletion as a cause as well, but that doesn't seem to be the case.
In a different column family, I just tried creating 2 new rows (with a bunch of columns each). Now I get:

```
cassandra.get_range(:OtherColumnFamily) # -> returns 0 rows
cassandra.get_range(:OtherColumnFamily, :key_count => 100) # -> returns 2 rows
```

The 2 new rows haven't been deleted at any point in time (though many other rows have been created and deleted in the past for that CF. However they do not show up, which is correct).

**Update:** I also had a peek inside `OtherColumnFamily` using `cassandra-cli`. I did

```
list OtherColumnFamily limit 2000;
```

and got 1646 rows, out of which only two have got columns. This is consistent with the concept of tombstones, but still does not explain why my first line above yields zero results.

In addition, all the 515 rows I was getting in my previous example had at least one non-empty column (and they were supposed to).

**Comment by rwjblue** [comment]
The behavior you describe is exactly the behavior I was referring to earlier. 

Your first query against :OtherCF fetches 100 rows (which is the READ_DEFAULT size) of which there are zero non-empty columns. 

Your second query performs multiple requests (in batches of 100) until it finds 100 keys to return (because of :key_count), but there were only two non-empty rows to return.

**Comment by Simbul** [comment]
Aha! Sorry it took me a while to figure it out.
I wrongly assumed `get_range` would - by default - return the first 100 non-empty rows it can find.
If I understand correctly, however, it fetches the first 100 rows - empty or otherwise - and - out of that - only returns the ones that are non-empty.

So I suppose to get what I expected I should always call get_range with an explicit `:key_count` parameter. Is that correct?

This behavior strikes me as a bit odd, but I guess I'm missing something: what is the rationale behind it?
