### ISSUE TITLE
Methods that accept keyspace arguments, shouldn't (?)

### ISSUE THREAD

**Issue by mcmire** [cassandra-rb/cassandra#157]
So here is a thought I had while glancing over some of the API. There are currently a few methods which accept keyspace arguments:
- create_keyspace
- drop_keyspace
- create_index
- drop_index

This is fine, but Cassandra.new already accepts a keyspace argument. That is, a Cassandra object represents the connection to a single keyspace. It does not make sense for methods within this class to manage other keyspaces, doing so is a kind of identity schism. If you want to manage another keyspace you should have to make a new Cassandra object.

This would obviously be a non-backward compatible change to remove these arguments, hence why I would like to get your (or other people's) thoughts. But, this is one of the several weird things about this gem I would like to see ironed out.

**Comment by natemueller** [comment]
I don't know.  Besides create_keyspace (since you can't use a keyspace until it exists) the extra keyspace arg seems redundant.  That said, requiring a separate TCP connection for every keyspace is not great either.  

The ability to easily make schema changes to multiple keyspaces from one connection makes setup and migration scripts a lot easier.  The feature is really part of the thrift protocol and this module just exposes it.  There is some overall inconsistency, but both the schema manipulation functions and the data access functions are internally consistent.  I don't think making them consistent with each other is necessarily a good thing and it's definitely not the biggest biggest problem this gem has right now.

**Comment by mcmire** [comment]
Sure. I mean, now that I look at the Thrift API it works the same way. Looks the idea is, use #set_keyspace to establish the current keyspace, and then whatever query methods going forward you use are scoped to that keyspace. I'm guessing #create_keyspace and #drop_keyspace are one-offs -- the keyspace could be anything -- hence the explicit keyspace argument. So that's the behavior the Cassandra class is wrapping, it looks like. Which is okay.

As for #create_index and #drop_index (which aren't in Thrift, they just wrap #update_column_family), I guess the thought was, well, they're schema methods, they should work the same way. Except #clear_column_family! _doesn't_ accept a keyspace argument, so you can't make that assumption. Not necessarily criticizing since I know those were recent additions. Just pointing out that the API is mushy at points.

But that's fair this isn't a big concern.
