### ISSUE TITLE
Support for cassandra 2.0

### ISSUE THREAD

**Issue by rubycut** [cassandra-rb/cassandra#198]
Any plans for that?

**Comment by psanford** [comment]
Do you just mean updated thrift bindings, or is there a specific feature you are looking for? 

Updating the thrift bindings is relatively easy, you just need to run the cassandra.thrift file (from cassandra proper's source tree) through the thrift compiler. Feel free to send a pull request.

In the mean time you should be able to use the 1.2 bindings against a 2.0 server without much difficulty. The C\* devs have been pretty good about maintaining backward compatibility in the thrift bindings since the 0.6->0.7 mess with passing the keyspace name to every function.

**Comment by rubycut** [comment]
Here is the file:

```
require 'cassandra/1.2'
client = Cassandra.new('demodb', '127.0.0.1:9160')
p client.version
p client.keyspaces
p client.schema_agreement?
client.each(:metrics) do |key|
  print key
end
```

Here is the output:

```
 ruby gem_test.rb 
"19.37.0"
["system", "demodb", "system_traces"]
true
/home/rubycut/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/cassandra-0.22.0/lib/cassandra/columns.rb:59:in `column_family_property': Invalid column family "metrics" (Cassandra::AccessError)
        from /home/rubycut/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/cassandra-0.22.0/lib/cassandra/columns.rb:44:in `column_name_class_for_key'
```

Here is the db:

```
cqlsh 
Connected to Test Cluster at localhost:9160.
[cqlsh 4.0.1 | Cassandra 2.0.1 | CQL spec 3.1.1 | Thrift protocol 19.37.0]
Use HELP for help.
cqlsh> use demodb;
cqlsh:demodb> select * from metrics LIMIT 1;

 server | metric   | date   | ts                       | value
--------+----------+--------+--------------------------+-------
server543 | load1min | 201310 | 2013-10-08 08:06:38+0200 |     3

(1 rows)
```

So metrics table is definitely there.

**Comment by psanford** [comment]
Did you create the CF from CQL? For a while there was a restriction that prevented you from accessing CFs created via CQL from the thrift interface. 

Can you try creating the CF using the thrift interface?

**Comment by rubycut** [comment]
In Cassandra 2.0, there are tables, there are no column families, as you can see from the output, metrics table is created.

I am pretty new to whole cassandra thingm I am not sure how to create CF using thrift interface.

**Comment by psanford** [comment]
A CQL table is an abstraction on top of column family, which is what causes the incompatibility between using the thrift interfaces and the CQL interface. If you want to stick to CQL you might want to try https://github.com/iconara/cql-rb

**Comment by rubycut** [comment]
I am already using cql-rb for testing, but in production I will need speed, which means I need this gem because it supports eventmachine.

**Comment by natemueller** [comment]
Sorry, but like @psanford said you can't mix CQL and thrift in Cassandra 2.0.  If you need to use this library in production you'll need to stop using CQL for testing and development.

**Comment by psanford** [comment]
I've confirmed that the 1.2 bindings work against a 2.0 server. 

Also you might be disappointed by the event machine support. It is true that there is an em class in thrift_client, but if you look at it you might notice that it uses a method called 'blocking_read' :(.  The problem is that there is no non-blocking mode in the thirft library for ruby. There was some effort made to get that working but it has never been merged: https://issues.apache.org/jira/browse/THRIFT-146.

**Comment by rubycut** [comment]
Ok, closing then. Thanks.
