### ISSUE TITLE
cassandra.insert cannot handle booleans

### ISSUE THREAD

**Issue by chrislbs** [cassandra-rb/cassandra#201]
The cqlsh DESCRIBE of my table returns this.

CREATE TABLE "USER" (
  key text PRIMARY KEY,
  "EMAIL" text,
  "FIRSTNAME" text,
  "LASTNAME" text,
  "USERNAME" text,
  "IS_ENABLED" boolean,
  "PASSWORD" text,
  "TIMEFORMAT" text
) WITH COMPACT STORAGE AND
  bloom_filter_fp_chance=0.010000 AND
  caching='KEYS_ONLY' AND
  comment='' AND
  dclocal_read_repair_chance=0.000000 AND
  gc_grace_seconds=864000 AND
  read_repair_chance=0.100000 AND
  replicate_on_write='true' AND
  populate_io_cache_on_flush='false' AND
  compaction={'class': 'SizeTieredCompactionStrategy'} AND
  compression={'sstable_compression': 'LZ4Compressor'};

When I run this code:

username = "admin"
admin_user = {
'USERNAME' => username,
'PASSWORD'=>'Plain Text',
'FIRSTNAME' => 'DEFAULT',
'LASTNAME' => 'USER',
'IS_ENABLED' => true
}

$cassandra.insert("USER", username, admin_user)

I get the error "Value should be a string."

When I run this code:

username = "admin"
admin_user = {
'USERNAME' => username,
'PASSWORD'=>'Plain Text',
'FIRSTNAME' => 'DEFAULT',
'LASTNAME' => 'USER',
'IS_ENABLED' => 'true'
}

$cassandra.insert("USER", username, admin_user)

I get the error "No live servers in [127.0.0.1:9160]."

If I remove the assignment to 'IS_ENABLED' it succeeds.

**Comment by natemueller** [comment]
You've got a couple issues.  You're seeing the "No live servers" error because your retry count is higher then the numbers of nodes in your ring.  This gem only shows the error it got on the last retry so if you drop that down you'll get something a lot more meaningful.

The boolean issue is an encoding problem.  This gem doesn't do any encoding for you.  Anything you want to insert into cassandra needs to be encoded in a way it understands.  The cassandra-cql gem has some good reference implementations.  For your particular case false is "\x00" and true is "\x01".
