### ISSUE TITLE
CQL 3 Support ?

### ISSUE THREAD

**Issue by algermissen** [cassandra-rb/cassandra#210]
Hi,

are you still actively developing this driver given most(?) people's preference for CQL 3 ?  

Is CQL 3 native support on your list? Or should I move over to iconara/cql-rb

Thanks,

Jan

**Comment by psanford** [comment]
We still use this library in production. We'll take bug fixes and features as people submit them. Since recent work on Cassandra has been on the CQL side of things we've mostly been merging bug fixes the past year. 

There are no plans to support CQL3 in this client. Cql-rb seems to be the preferred CQL3 native client for ruby.
