### ISSUE TITLE
Using nonexistent keyspace gives unexpected error message

### ISSUE THREAD

**Issue by stephenjudkins** [cassandra-rb/cassandra#5]
Using a nonexistent keyspace gives a stack overflow error, instead of an AccessError as is intended.

Commit at http://github.com/stephenjudkins/cassandra/commit/4bb123dee625bfb22105b0ec8acb3682df1a780c fixes this and adds a test.  Pull request has been sent.

**Comment by ryanking** [comment]
commited! thanks.

**Comment by idearise** [comment]
Yes, that confused me a bit since the debug instance's conf/storage-conf.xml file is the default, out-of-the-box configuration but the debug instance is actually configured through the cassandra_helper with the cassandra gem's storage-conf.xml file.  

You can create a client instance for a keyspace and not get an error message if it doesn't exist.  However, when inserting or querying, the current error being returned is "No live servers"...this doesn't jump out to a newbie like me as meaning that it can't find the keyspace being specified in an insert or query.  Just my noob feedback!
